# Generated by Django 4.2.4 on 2023-09-11 08:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_animal_animal_class_alter_animal_country_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number', models.CharField(default='+375 (29) XXX-XX-XX', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be in the format: '+375 (29) XXX-XX-XX'", regex='^\\+375 \\(\\d{2}\\) \\d{3}-\\d{2}-\\d{2}$')])),
                ('username', models.CharField(default='', max_length=30)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
        migrations.AddField(
            model_name='staffer',
            name='description',
            field=models.CharField(default='', max_length=300),
        ),
        migrations.AddField(
            model_name='staffer',
            name='photo',
            field=models.URLField(default='https://i.pinimg.com/originals/eb/b4/39/ebb439b95577b6289fb1659635eed377.png'),
        ),
    ]
