# Generated by Django 4.2.4 on 2023-09-11 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_client_staffer_description_staffer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffer',
            name='description',
        ),
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='post',
            name='requirements',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
