from django.urls import path, include
from . import views
from django.contrib.auth.views import PasswordChangeView

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/registration/', views.registration, name='registration'),
    path('animals/', views.AnimalListView.as_view(), name='animals'),
    path('animals/<int:id>/', views.AnimalDetailsView.as_view(), name='animal'),
    path('placements/', views.PlacementListView.as_view(), name='placements'),
    path('placements/<int:id>/', views.PlacementDetailsView.as_view(), name='placement'),
    path('placements/<int:id>/animals/', views.PlacementAnimalsView.as_view(), name='placement_animals'),
    path('staff/', views.StafferListView.as_view(), name='staff'),
    path('staff/<int:id>/', views.StafferDetailsView.as_view(), name='staffer'),
    path('staff/<int:id>/animals/', views.StafferAnimalsView.as_view(), name='staffer_animals'),
    path('staff/<int:id>/placements/', views.StafferPlacementsView.as_view(), name='staffer_placements'),
    path('personal/', views.PersonalAccountView.as_view(), name='personal_account'),
    path('personal/profile/', views.UserProfileView.as_view(), name='user_profile'),
    path('personal/animals/', views.UserAnimalsView.as_view(), name='user_animals'),
    path('personal/placements/', views.UserPlacementsView.as_view(), name='user_placements'),
    path('personal/settings/', views.UserUpdateView.as_view(), name='user_settings'),
    path('animals/<int:pk>/edit/', views.AnimalUpdate.as_view(), name='edit_animal'),
    path('animals/add/', views.AnimalCreate.as_view(), name='add_animal'),
    path('animals/<int:pk>/delete/', views.AnimalDelete.as_view(), name='delete_animal'),
    path('placements/<int:pk>/edit/', views.PlacementUpdate.as_view(), name='edit_placement'),
    path('placements/add/', views.PlacementCreate.as_view(), name='add_placement'),
    path('placements/<int:pk>/delete/', views.PlacementDelete.as_view(), name='delete_placement'),
    path('<int:id>/password/', PasswordChangeView.as_view(success_url='/main/personal/'), name='password_change'),
    path('diagram/', views.DiagramView.as_view(), name='diagram'),
    path('static_info/', views.StaticInfoView.as_view(), name='static_info'),
    path('about_us/', views.AboutUsView.as_view(), name='about_us'),
    path('vacancies/', views.VacancyListView.as_view(), name='vacancies'),
    path('questions/', views.QuestionListView.as_view(), name='questions'),
    path('reviews/', views.ReviewListView.as_view(), name='reviews'),
    path('articles/', views.ArticleListView.as_view(), name='news'),
    path('articles/<int:id>/', views.ArticleView.as_view(), name='article'),
    path('coupons/', views.CouponListView.as_view(), name='coupons'),
    path('privacy_policy/', views.PrivacyPolicyView.as_view(), name='privacy_policy'),
    path('reviews/add/', views.ReviewCreate.as_view(), name='add_review'),
    path('other/', views.OtherView.as_view(), name='other'),

    # for JavaScript things
    path('other/text_change/', views.TextChangeView.as_view(), name='text_change'),
    path('other/age_calculator/', views.AgeCalculatorView.as_view(), name='age_calculator'),
    path('other/interactive_table/', views.InteractiveTableView.as_view(), name='interactive_table'),
    path('other/scrolling_animation/', views.ScrollingAnimationView.as_view(), name='scrolling_animation'),
    path('other/associative_array/', views.AssociativeArrayView.as_view(), name='associative_array'),
    path('other/price_calculation/', views.PriceCalculationView.as_view(), name='price_calculation'),
    path('other/autoplay_carousel/', views.AutoplayCarouselView.as_view(), name='autoplay_carousel'),
]
